### ISSUE TITLE
zh.yml file with the first line wrongly set to en

### ISSUE THREAD

**Issue by zl2705** [dominch/redmine_highlightjs#17]
redmine_highlightjs/config/locales/zh.yml file with the first line wrongly set to en.
when plugin into redmine will get error like this:
Completed 500 Internal Server Error in 166ms

ActionView::Template::Error (translation missing: en.date.formats.default):

**Comment by uaqben** [comment]
#20 should fix this.

**Comment by dominch** [comment]
Hello, yes, this is it. Thanks @uaqben for pull request. Sorry for such delay :)
