### ISSUE TITLE
Code block disappeared in IE8

### ISSUE THREAD

**Issue by aliramw** [dominch/redmine_highlightjs#9]
I know that IE8 is devil... But, all of our company's laptops use IE8 as the standard working browser.

Highlight.js does not support IE8, so I think maybe the plugin should add some compatible code not to use highlight.js in IE8.

styles in fixes.css made code blocks hidden in IE8...

**Comment by Krakozaber** [comment]
-> https://github.com/isagalaev/highlight.js

**Comment by dominch** [comment]
HighlightJS won't support IE8, they dropped that two years ago and don't plan to continue that. 
It is easy to turn off highlighting and show blocks, but it's harder to conditionally turn on CodeRay again. I'll take a look what can be done about it,

**Comment by dominch** [comment]
@marilawang Please check out version from [dev branch](/dominch/redmine_highlightjs/tree/dev)
it should turn off plugin for few old browsers

**Comment by dominch** [comment]
Change is released in 1.0.2, if You still have a problem  - let me know in new issue.

**Comment by aliramw** [comment]
the disappearing problem fixed, but codeRay is not working in IE8.

**Comment by dominch** [comment]
@marilawang please recheck `dev` branch, it seems that 1.0.2 had small issue with CodeRay switch.
